export const API_CONFIG = {
  OPENAI_API_KEY: process.env.OPENAI_API_KEY,
  CHAT_SERVICE: process.env.CHAT_SERVICE,
  EMBEDDINGS_SERVICE: process.env.EMBEDDINGS_SERVICE,
  PARKS_SERVICE: process.env.PARKS_SERVICE,
  EMBEDDING_MODEL: process.env.EMBEDDING_MODEL,
  CHAT_MODEL: process.env.CHAT_MODEL,
  NUM_SIMILAR_PARKS: process.env.NUM_SIMILAR_PARKS,
  MAX_TOKENS: 2048,
  ECOQUERAI_CONTEXT_1: process.env.ECOQUERAI_CONTEXT_1,
  ECOQUERAI_CONTEXT_2: process.env.ECOQUERAI_CONTEXT_2,
  QUER_CONTEXT: process.env.QUER_CONTEXT,
};
